## One Hot Encoding

In [2]:
import numpy as np

In [3]:
sentence = "I have a book and I like romance"
token = sentence.split()
print(token)

['I', 'have', 'a', 'book', 'and', 'I', 'like', 'romance']


In [8]:
# create vocabulary
word_set = list(set(token))
word_dict = {w:i for i, w in enumerate(word_set)}
word_dict

{'I': 0, 'like': 1, 'and': 2, 'have': 3, 'romance': 4, 'a': 5, 'book': 6}

In [13]:
def one_hot_encoding(word, word_dict):
    one_hot_vector = np.zeros(len(word_dict)) # 단어사전 길이만크의 0벡터 생성
    one_hot_vector[word_dict[word]] = 1 # 해당하는 단어의 index 자리에 1 부여
    return one_hot_vector

In [15]:
one_hot_encoding('I', word_dict)

array([1., 0., 0., 0., 0., 0., 0.])

In [16]:
one_hot_encoding('romance', word_dict)

array([0., 0., 0., 0., 1., 0., 0.])

In [29]:
word_list = []
for w in token:
    word_list.append(one_hot_encoding(w, word_dict))
print(np.array(word_list)) ## full sentence onehotencoding

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]
